// PWA web app manifest — Next.js App Router file convention.
//
// Why we have a PWA: it's a home-screen badge that gets dads back to Boss
// Daddy in one tap — the familiar app-icon mental model for quick return to
// the site (reviews, guides, gear). It is NOT a "tools app"; tools are a
// complement, so the icon lands on the homepage, not any single tool.
//
// Icons are pre-rendered, correctly-sized PNGs (generated by downscaling the
// 1024² source app/icon.png — see public/icon-192.png / icon-512.png). The
// maskable variant pads the logo onto the dark splash color so Android's
// adaptive-icon circle mask never clips it. The apple-touch-icon is emitted
// separately by Next.js's app/apple-icon.png file convention — don't declare
// it here (it was previously listed with a wrong 180×180 size on a 1024² file).
//
// Color cohesion: background_color (splash body), manifest theme_color (splash
// top bar / task-switcher), and viewport.themeColor in app/layout.tsx are all
// #0a0a0a — a single dark value so launch shows no orange→dark flash.

import type { MetadataRoute } from 'next'

export default function manifest(): MetadataRoute.Manifest {
  return {
    id:                   '/',
    name:                 'Boss Daddy Life',
    short_name:           'Boss Daddy',
    description:          'Honest gear reviews, guides, and tools for real dads — Boss Daddy, one tap from your home screen.',
    lang:                 'en',
    start_url:            '/',
    scope:                '/',
    display:              'standalone',
    orientation:          'portrait',
    background_color:     '#0a0a0a',
    theme_color:          '#0a0a0a',
    categories:           ['lifestyle', 'shopping', 'productivity'],
    icons: [
      {
        src:     '/icon-192.png',
        sizes:   '192x192',
        type:    'image/png',
        purpose: 'any',
      },
      {
        src:     '/icon-512.png',
        sizes:   '512x512',
        type:    'image/png',
        purpose: 'any',
      },
      {
        src:     '/maskable-512.png',
        sizes:   '512x512',
        type:    'image/png',
        purpose: 'maskable',
      },
    ],
  }
}
